"""Write frontend/metrics.json — a static snapshot of the reference dataset.

The landing page reads its figures from the live API. On a static host there may
be no API reachable, so it falls back to this file rather than showing dashes.

The snapshot is generated from the same evaluation the README quotes, so the
fallback is real measured output, not placeholder text. Regenerate it whenever
the detection logic or the reference dataset changes:

    .venv/Scripts/python.exe scripts/build_metrics.py
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))

import evaluate                      # noqa: E402
from workspace import build_workspace  # noqa: E402

REFERENCE_SEED = 26


def main() -> None:
    ws = build_workspace(REFERENCE_SEED)
    ws.rescan(lambda w, c: c)
    ev = evaluate.compute(ws.graph, ws.truth, ws.model, ws.report)

    chains = ws.visible_chains()
    live = [c for c in chains if c["recoverable"]]
    gaps = sorted(c["elapsed_minutes"] for c in chains) or [0]
    flagged = int((ws.model.scores >= 0.5).sum()) if ws.model.scores is not None else 0

    snapshot = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "seed": REFERENCE_SEED,
        "note": "Static snapshot of the reference dataset, used when no API is "
                "reachable. Generated by scripts/build_metrics.py.",
        "overview": {
            "dataset": ws.label,
            "seed": ws.seed,
            "transactions": int(len(ws.graph.txns)),
            "accounts": int(len(ws.graph.accounts)),
            "active_chains": len(chains),
            "freezable_chains": len(live),
            "cashed_out_chains": len(chains) - len(live),
            "dismissed_chains": 0,
            "funds_recoverable": round(sum(c["amount_at_end"] for c in live), 2),
            "funds_lost": round(sum(c["amount_at_end"] for c in chains
                                    if not c["recoverable"]), 2),
            "median_chain_minutes": gaps[len(gaps) // 2],
            "accounts_flagged": flagged,
            "injected_chains": int(len(ws.truth)),
            "model": ws.report.as_dict(),
            "baseline": ws.model.baseline_report,
        },
        "evaluation": ev,
    }

    out = ROOT / "frontend" / "metrics.json"
    out.write_text(json.dumps(snapshot, indent=2), encoding="utf-8")

    o, w, s = snapshot["overview"], ev["chain_walk"], ev["proactive_scan"]
    print(f"wrote {out.relative_to(ROOT)}")
    print(f"  dataset {o['dataset']}  {o['transactions']:,} txns  "
          f"{o['accounts']:,} accounts  {o['active_chains']} chains")
    print(f"  end-node accuracy {w['end_node_accuracy']:.1%}  "
          f"scan recall {s['recall_vs_injected']:.1%}  "
          f"clean prefix {s['clean_prefix']}")
    print(f"  classifier AUC {ev['risk_model']['roc_auc']} "
          f"vs baseline {ev['baseline']['roc_auc']}")


if __name__ == "__main__":
    main()
